name: nutrio
description: Scan products. Eat smarter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^5.2.3
  dio: ^5.4.3
  flutter_riverpod: ^2.5.1
  cached_network_image: ^3.3.1
  percent_indicator: ^4.2.3
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
